// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Add'](arg1, arg2, arg3);
}

export function Delete(arg1) {
  return window['go']['backend']['App']['Delete'](arg1);
}

export function List() {
  return window['go']['backend']['App']['List']();
}

export function Toggle(arg1) {
  return window['go']['backend']['App']['Toggle'](arg1);
}

export function Update(arg1) {
  return window['go']['backend']['App']['Update'](arg1);
}
