// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Add(arg1:string,arg2:any,arg3:string):Promise<models.Task>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<models.Task>>;

export function Toggle(arg1:string):Promise<void>;

export function Update(arg1:models.Task):Promise<void>;
